-- CO SO DU LIEU QUAN LY HOC TAP
conn qlhs/123456;
alter session set "_oracle_script" = true;  
set current_schema = qlhs ; 

-- Xoa cac bang
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PREREQUISITE';
    EXECUTE IMMEDIATE 'DROP TABLE GRADE_REPORT';
    EXECUTE IMMEDIATE 'DROP TABLE SECTION';
    EXECUTE IMMEDIATE 'DROP TABLE COURSE';
    EXECUTE IMMEDIATE 'DROP TABLE STUDENT';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/


-- Tao cau truc bang
-- STUDENT
CREATE TABLE STUDENT (
    Student_number NUMBER(2) PRIMARY KEY,
    Name VARCHAR2(10),
    Class NUMBER,
    Major VARCHAR2(10)
);

-- COURSE
CREATE TABLE COURSE
(
    Course_number VARCHAR2(10) PRIMARY KEY,
    Course_name VARCHAR2(30),
    Credit_hours NUMBER,
    Department VARCHAR2(10)
);

-- SECTION
CREATE TABLE SECTION
(
    Section_identifier NUMBER(3) PRIMARY KEY,
    Course_number VARCHAR2(10),
    Semester VARCHAR2(10),
    Year NUMBER(2),
    Instructor VARCHAR2(10)
);

-- GRADE_REPORT
CREATE TABLE GRADE_REPORT 
(
    Student_number NUMBER(2),
    Section_identifier NUMBER(3),
    Grade VARCHAR2(2)
);

-- PREREQUISITE
CREATE TABLE PREREQUISITE 
(
    Course_number VARCHAR2(10),
    Prerequisite_number VARCHAR2(10)
);

-- Rang buoc khoa ngoai
-- SECTION
ALTER TABLE SECTION ADD CONSTRAINT FK_SE FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number);

-- GRADE_REPORT
ALTER TABLE GRADE_REPORT ADD
(
    CONSTRAINT FK_GR1 FOREIGN KEY (Student_number) REFERENCES STUDENT(Student_number), 
    CONSTRAINT FK_GR2 FOREIGN KEY (Section_identifier) REFERENCES SECTION(Section_identifier)
);

-- PREREQUISITE
ALTER TABLE PREREQUISITE ADD
(
    CONSTRAINT FK_P1 FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number),
    CONSTRAINT FK_P2 FOREIGN KEY (Prerequisite_number) REFERENCES COURSE(Course_number)
);


-- Nhap du lieu
-- STUDENT
INSERT ALL
    INTO STUDENT VALUES (17, 'Smith', 1, 'CS')
    INTO STUDENT VALUES (8, 'Brown', 2, 'CS')
SELECT * FROM DUAL;

-- COURSE
INSERT ALL
    INTO COURSE VALUES ('CS1310', 'Intro to Computer Science', 4, 'CS')
    INTO COURSE VALUES ('CS3320', 'Data Structures', 4, 'CS')
    INTO COURSE VALUES ('MATH2410', 'Discrete Mathematics', 3, 'MATH')
    INTO COURSE VALUES ('CS3380', 'Database', 3, 'CS')
SELECT * FROM DUAL;

-- SECTION
INSERT ALL
    INTO SECTION VALUES (85, 'MATH2410', 'Fall', 07, 'King')
    INTO SECTION VALUES (92, 'CS1310', 'Fall', 07, 'Anderson')
    INTO SECTION VALUES (102, 'CS3320', 'Spring', 08, 'Kruth')
    INTO SECTION VALUES (112, 'MATH2410', 'Fall', 08, 'Chang')
    INTO SECTION VALUES (119, 'CS1310', 'Fall', 08, 'Anderson')
    INTO SECTION VALUES (135, 'CS3380', 'Fall', 08, 'Stone')
SELECT * FROM DUAL;

-- GRADE_REPORT
INSERT ALL
    INTO GRADE_REPORT VALUES (17, 112, 'B')
    INTO GRADE_REPORT VALUES (17, 119, 'C')
    INTO GRADE_REPORT VALUES (8, 85, 'A')
    INTO GRADE_REPORT VALUES (8, 92, 'A')
    INTO GRADE_REPORT VALUES (8, 102, 'B')
    INTO GRADE_REPORT VALUES (8, 135, 'A')
SELECT * FROM DUAL;

-- PREREQUISITE
INSERT ALL
    INTO PREREQUISITE VALUES ('CS3380', 'CS3320')
    INTO PREREQUISITE VALUES ('CS3380', 'MATH2410')
    INTO PREREQUISITE VALUES ('CS3320', 'CS1310')
SELECT * FROM DUAL;


-- Kiem tra du lieu
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SECTION;
SELECT * FROM GRADE_REPORT;
SELECT * FROM PREREQUISITE;
