set echo on ; 

alter session set "_oracle_script" = true ; 

CREATE ROLE STUDENT ;

CREATE ROLE INSTRUCTOR ; 

CREATE ROLE TRAINING_SPECIALIST ; 

CREATE ROLE EXAM_STAFF ; 

CREATE ROLE STUDENT_SERVICES_SPECIALIST ; 

CREATE ROLE ACADEMIC_ADMIN;

