conn qlhs/123456;
alter session set "_oracle_script" = true; 

-- INITIAL USER IN DATABASE : 
EXEC USP_CREATE_INSTRUCTOR_USER;
EXEC USP_CREATE_STUDENT_USER; 

-- GRANT FOR ROLE  ; 
-- GRANT FOR STUDENT ; 
GRANT SELECT ON QLHS.VW_STUDENT_ON_SECTION TO STUDENT;
GRANT SELECT ON QLHS.VW_STUDENT_ON_COURSE TO STUDENT; 
GRANT SELECT ON QLHS.VW_STUDENT_ON_STUDENT TO STUDENT;

GRANT SELECT ON QLHS.VW_STUDENT_ON_GRADE_REPORT TO STUDENT; 

GRANT INSERT ON QLHS.VW_STUDENT_ON_GRADE_REPORT TO STUDENT ;

-- GRANT FOR INSTRUCTOR ; 
GRANT SELECT ON QLHS.VW_INSTRUCTOR_ON_GRADE_REPORT TO INSTRUCTOR ; 
GRANT SELECT ON QLHS.VW_INSTRUCTOR_ON_SECTION TO INSTRUCTOR ;

-- GRANT FOR TRAINING_SPECIALIST ; 
GRANT INSERT, UPDATE , DELETE ON QLHS.COURSE TO TRAINING_SPECIALIST ; 
GRANT INSERT , UPDATE , DELETE ON QLHS.PREREQUISITE TO TRAINING_SPECIALIST ;
GRANT INSERT , UPDATE, DELETE ON QLHS.SECTION TO TRAINING_SPECIALIST;
GRANT UPDATE ON QLHS.STUDENT(MAJOR) TO TRAINING_SPECIALIST; 

--GRANT FOR EXAM_SPECIALLIST ; 
GRANT UPDATE ON QLHS.GRADE_REPORT(GRADE) TO EXAM_SPECIALLIST; 

-- GRANT FOR STUDENT_SERVICES_SPECIALIST ; 
GRANT INSERT ON QLHS.STUDENT TO STUDENT_SERVICES_SPECIALIST; 

-- GRANT FOR 
GRANT SELECT ON SCHEMA :: QLHS TO ACADEMIC_ADMIN; 

-- GRANT FOR USER ; 
EXEC USP_GRANT_ROLE_FOR_USER ('RL_QLHS_STUDENT' , 'STUDENT');
EXEC USP_GRANT_ROLE_FOR_USER('RL_QLHS_INSTRUCTOR', 'INSTRUCTOR'); 
