set echo on ; /
alter session set current_schema = QLHS;
alter session set  "_oracle_script" = true; 
set pause off; 

-- SET VIEW FOR STUDENT ; 

-- XEM BANG SECION TRU TRUONG INSTRUCTOR ; 

CREATE OR REPLACE VIEW VW_STUDENT_ON_SECTION 
AS
SELECT SECTION_IDENTIFIER , COURSE_NUMBER , SEMESTER , YEAR FROM SECTION ; 
/

-- XEM BANG COURSE, PREREQUISITE 

CREATE OR REPLACE VIEW VW_STUDENT_ON_COURSE 
AS 
SELECT * FROM COURSE ; 
/

CREATE OR REPLACE VIEW VW_STUDENT_ON_PREREQUISITE 
AS 
SELECT * FROM PREREQUISITE ; 
/

--XEM THONG TIN LIEN QUAN DEN BAN THAN TREN BANG STUDENT ; 

CREATE OR REPLACE VIEW VW_STUDENT_ON_STUDENT 
AS 
SELECT * FROM STUDENT WHERE 
'RL_QLHS_STUDENT_' || STUDENT_NUMBER = SYS_CONTEXT('USERENV' , 'SESSION_USER');
/

-- XEM DONG DU LIEU LIEN QUAN TOI BAN THAN GRADE_REPORT ; 
CREATE OR REPLACE VIEW VW_STUDENT_ON_GRADE_REPORT 
AS 
SELECT * FROM GRADE_REPORT WHERE 
'RL_QLHS_STUDENT_' || STUDENT_NUMBER = SYS_CONTEXT('USERENV' , 'SESSION_USER');

-- THEM THONG TIN TREN GRADE_REPORT 
CREATE OR REPLACE TRIGGER TRG_STUDENT_INSERT_ON_GRADE_REPORT
AS 
SELECT * FROM GRADE_REPORT WHERE 