set echo on ; 

alter session set "_oracle_script" = true ; 

CREATE ROLE STUDENT ;

CREATE ROLE INSTRUCTOR ; 

-- GRANT FOR STUDENT ; 
GRANT SELECT ON QLHS.VW_STUDENT_ON_SECTION TO STUDENT;
GRANT SELECT ON QLHS.VW_STUDENT_ON_COURSE TO STUDENT; 
GRANT SELECT ON QLHS.VW_STUDENT_ON_STUDENT TO STUDENT;

-- GRANT FOR INSTRUCTOR ; 

