set echo on ; /
alter session set current_schema = QLHS;
alter session set  "_oracle_script" = true; 
set pause off; 

-- SET VIEW FOR STUDENT ; 

-- XEM BANG SECION TRU TRUONG INSTRUCTOR ; 

CREATE OR REPLACE VIEW VW_STUDENT_ON_SECTION 
AS
SELECT SECTION_IDENTIFIER , COURSE_NUMBER , SEMESTER , YEAR FROM SECTION ; 
/

-- XEM BANG COURSE, PREREQUISITE 

CREATE OR REPLACE VIEW VW_STUDENT_ON_COURSE 
AS 
SELECT * FROM COURSE ; 
/

CREATE OR REPLACE VIEW VW_STUDENT_ON_PREREQUISITE 
AS 
SELECT * FROM PREREQUISITE ; 
/

--XEM THONG TIN LIEN QUAN DEN BAN THAN TREN BANG STUDENT ; 

CREATE OR REPLACE VIEW VW_STUDENT_ON_STUDENT 
AS 
SELECT * FROM STUDENT WHERE 
'RL_QLHS_STUDENT_' || STUDENT_NUMBER = SYS_CONTEXT('USERENV' , 'SESSION_USER');
/

-- XEM DONG DU LIEU LIEN QUAN TOI BAN THAN GRADE_REPORT ; 
CREATE OR REPLACE VIEW VW_STUDENT_ON_GRADE_REPORT 
AS 
SELECT * FROM GRADE_REPORT WHERE 
'RL_QLHS_STUDENT_' || STUDENT_NUMBER = SYS_CONTEXT('USERENV' , 'SESSION_USER');

-- THEM THONG TIN TREN GRADE_REPORT 
CREATE OR REPLACE TRIGGER TRG_STUDENT_INSERT_ON_GRADE_REPORT
    INSTEAD OF INSERT ON VW_STUDENT_ON_GRADE_REPORT
    FOR EACH ROW
DECLARE 
    STUDENT_USER NUMBER ;
    TXT EXCEPTION ; 
    ERR_MSG VARCHAR(200);
    START_ENROLL DATE ; 
    END_ENROLL DATE ; 
    CUR_DATE_ENROLL DATE ;
BEGIN 
    STUDENT_USER := REPLACE (SYS_CONTEXT('USERENV' , 'SESSION_USER'), 'RL_QLHS_STUDENT_', '');

    START_ENROLL := (SELECT TOP 1 (START_TIME) FROM COURSE_REGIS_TIMELINE); 
    END_ENROLL := (SELECT TOP 1 (END_TIME) FROM COURSE_REGIS_TIMELINE);
    CUR_DATE_ENROLL := SYS_CONTEXT('USERENV','NLS_DATE_FORMAT')

    IF NOT EXISTS (SELECT * FROM SECTION S WHERE SECTION_IDENTIFIER  = S.SECTION_IDENTIFIER) THEN 
        ERR_MSG := 'INVALID SECTION IDENTIFIER!!!';
        RAISE TXT;
    ELSE IF (START_ENROLL > CUR_DATE_ENROLL || END_ENROLL < CUR_DATE_ENROLL) 
        ERR_MSG := 'OUT OF TIME TO ENROL!!!';
        RAISE TXT;
    ELSE 
        INSERT INTO GRADE_REPORT (STUDENT_NUMBER , SECTION_IDENTIFIER)
        VALUES (STUDENT_USER, SECTION_IDENTIFIER);
        COMMIT ;
    END IF ;

    EXCEPTION 
        WHEN TXT THEN 
            DBMS_OUTPUT.PUT_LINE(ERR_MSG);
END;
        